### ISSUE TITLE
STF Sound not working correctly

### ISSUE THREAD

**Issue by sascha-daehne** [Openvario/variod#16]
While my first test flight I tested the stf mode on my Openvario, build with the newest XCSOAR from 4.5.2020 and equivalent variod from the same date. The pulsaudio driver seems to be used.
The vario mode works good, but by switching to STF(Speed to fly) mode their is only a continouse noise, not changing by different climb values or speeds.

**Comment by kedder** [comment]
I wonder if this related to #15

**Comment by iglesiasmarianod** [comment]
Hi @condoratberlin, perhaps my question is trivial.
Did you have correct IAS indication in XCSoar?
Did it show a value or "---"?

**Comment by sascha-daehne** [comment]
Ok, i checkt the IAS at my next flight and it indeed shows 460kph. Nice but not true. At my second flight (removing the panel in between) I saw the correct value at IAS and the STF works. So i close this issue. It seems related to the sensors or the pneumatic connection in my glider.
