### ISSUE TITLE
Improvements for PR #19

### ISSUE THREAD

**Issue by linuxianer99** [Openvario/variod#28]
- Change utils to plain C
- In stf.c check calculations and add comments where theory came from

**Comment by bomilkar** [comment]
Will do, maybe over the week end.
I'm planning to address https://github.com/Openvario/variod/issues/20 at the same time.
OK?

@kedder : FYI

**Comment by linuxianer99** [comment]
@bomilkar :
Please address only one issue per PR !!
Please break down the commits in nice small reviewable pieces !

We want to improve this ;-)
