### ISSUE TITLE
Sound problems when switching between Vario and STF mode

### ISSUE THREAD

**Issue by eku60** [Openvario/variod#39]
Hello,

I have created an issue on sensord, but found that soundproblems are discussed here. Maybe ist is better placed here?
When switching from vario mode to stf mode sound disappears. When switching back to vario mode you can hear soom crack in the speaker.
You will have to restart XCSoar or to deactivate and activate the openvario connection in NMEA-menu to get vario sound again.
Switvching worked with 20193 but not with 21028 from Blaubart.
Used ist a SteFly OV with sensorboard.

Regards
eku60

**Comment by eku60** [comment]
Update: Tested image 20309. Switching works, the problem seems to be newer.

**Comment by hpmax** [comment]
It was a remarkably stupid bug...  It's fixed now in hpmax/variod.  I am putting in a PR.
