### ISSUE TITLE
how are the 3 processes supposed to behave?

### ISSUE THREAD

**Issue by bomilkar** [Openvario/variod#5]
If everything is going well, there are 3 processes running: xcsoar, variod, sensord.
They talk with each other through ports. So far so good.
But what is supposed to happen if one of them stops?
Or is there a particular sequence in which the 3 have to start?
I have not seen any documentation on this. Can someone point me at it? Or tell me what the original plan was?

If there is no documentation on it and no written plan, then I suggest this:
start variod first, then start sensord
xcsoar is then free to start, stop, start, ... as any time. It just reconnects to variod.

if sensord stops, should variod wait for it to come back on line?
Or should both be restarted, variod first, then sensord ??

@kedder, @iglesiasmarianod what do you think??

**Comment by kedder** [comment]
I think it is better not to assume any particular start order - sensord and variod are services managed by systemd, so systemd is allowed to start and restart them at any time (e.g. if they die or if user asks to do that).  Both of these services should be able to gracefully handle missing or dropped connections from their peers.
