### ISSUE TITLE
testbench for variod

### ISSUE THREAD

**Issue by bomilkar** [Openvario/variod#7]
I've been testing variod quite a bit over the past couple of days. One of the issues I came across is the lack of a (reproducible) test environment. For instance a testbench including a stimulus generator and a results analyzer. I have written a simple tool which sends $POV,E,-1.76,P,955.24,Q,658.00*3A sentences. But that's not quite enough for a (semi)automated testbench.

It occurred to me I might replay a recorded NMEA file.
XCSoar generates an NMEA log if one turns on Setup-Logger-NMEA_logger.
The tool would read lines from this NMEA log, keeping track of the time information (for instance from the $GPRMC sentences) to make sure runs at "normal" seed. (Without this time keeping, we might as well use nc to replay the log file.)

As a result, we would have a tool to generate test pattern to variod. We can capture and analyze log files from variod to see if it behaves as expected.

Is it worth the effort, or is it just me who would use it (sometimes)?

**Comment by kedder** [comment]
This is something I miss a lot in variod. In general - ability to test variod on your laptop without having to mess with openvario hardware.

**Comment by bomilkar** [comment]
I think we should have an extra repository: Openvario/variod-testbench
I can upload what I got as initial revision. And everybody is free to add, divert, ...
For now, it's just a handful of files. But that can quickly change.

**Comment by kedder** [comment]
To me extra git repo looks like an overkill, I think it can live inside this project, in a separate dir, if you want.

**Comment by bomilkar** [comment]
An extra dir sounds fine.
I'll do it as soon as I have something useful.

**Comment by bomilkar** [comment]
Here is my first stab at it: https://github.com/Openvario/variod/pull/10

**Comment by bomilkar** [comment]
@iglesiasmarianod you might find this useful to pin down the issue(s) you are currently chasing.

**Comment by bomilkar** [comment]
Created a new and clean PR for it: https://github.com/Openvario/variod/pull/12

**Comment by kedder** [comment]
@bomilkar  can we close this?
